# Generated by Django 5.0.6 on 2024-06-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_employees', '0003_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('awardid', models.AutoField(primary_key=True, serialize=False)),
                ('award_evaluatorname', models.CharField(max_length=40)),
                ('award_evaluateename', models.CharField(max_length=40)),
                ('purposeid', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=400)),
                ('advisorname', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='counter',
            field=models.IntegerField(default=10),
        ),
    ]
