# Generated by Django 5.0.6 on 2024-06-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_employees', '0006_alter_notification_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='Status',
            field=models.IntegerField(choices=[(0, 'Reject'), (1, 'Approe')], default=0),
        ),
    ]
