# Generated by Django 5.0.6 on 2024-06-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_employees', '0008_remove_award_award_evaluateename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='advisorname',
        ),
        migrations.AddField(
            model_name='award',
            name='advisorid',
            field=models.IntegerField(default=0),
        ),
    ]
