# Generated by Django 5.0.6 on 2024-06-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_employees', '0009_remove_award_advisorname_award_advisorid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='Status',
            field=models.IntegerField(default=0),
        ),
    ]
