# Generated by Django 5.0.6 on 2024-07-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rate_employees', '0010_alter_award_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='remark',
            field=models.CharField(default='NONE$', max_length=50),
        ),
    ]
